name: 'generate dbt docs'
on:
  pull_request:
    types:
      - labeled

jobs:
  generate-docs:
    if: github.event.label.name == 'docs:ready'
    uses: fivetran-catfritz/docs_generator_test/.github/workflows/generate_docs.yml@main
    with:
      schema_var_name: recharge_schema
    secrets: inherit
